version = 1

exclude_patterns = ["**/*.pb.go", "vendor/**"]
test_patterns = ["**/*_test.go", "test/**"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/letsencrypt/boulder"]
  dependencies_vendored = true
